# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'nuget' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '07:45'
      timezone: 'America/Chicago'
    labels:
      - 'nuget'
      - 'dependabot'
    target-branch: 'main'
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      separator: '-'
    commit-message:
      prefix: '⬆️ '
    groups:
      mtd:
        patterns:
          - 'Mtd.*'
        update-types:
          - minor
          - patch
      ef:
        patterns:
            - 'Microsoft.EntityFrameworkCore.*'
        update-types:
        - minor
        - patch
      logging:
        patterns:
            - 'Serilog.*'
            - 'Microsoft.Extensions.Logging'
            - 'Microsoft.Extensions.Logging.*'
            - 'Seq.*'
        update-types:
        - minor
        - patch
      minor:
        update-types:
          - minor
    registries:
        - github-registry

registries:
  github-registry:
    type: 'nuget-feed'
    url: 'https://nuget.pkg.github.com/CUMTD/index.json'
    username: 'x-access-token'
    password: '${{secrets.GITHUB_TOKEN}}'